services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "${MYSQL_DATABASE}"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/learn-bash_dump.sql
    networks:
      - backend

  client:
    image: mysql:8.0
    command: ["sleep", "infinity"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./dump.sql:/com.docker.devenvironments.code/dump.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data: