services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - backend

  client:
    image: mysql:8.0
    command: ["sleep", "infinity"]
    env_file:
      - ./.env
    volumes:
      - ./dump.sql:/com.docker.devenvironments.code/testing-mysql/dump.sql
    depends_on:
      db:
        condition: service_started
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data: